spring:
  application:
    name: demin-coupon-service

  datasource:
    url: jdbc:postgresql://localhost:5432/common_db
    username: common_user
    password: common_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: coupon